/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.Registro;

/**
 *
 * @author USUARIO
 */
public class menu extends javax.swing.JFrame implements ItemListener {

    
    
    ingresovehiculo ventanaingreso;
    altacliente ventanaaltacliente;
    altaempleado ventanaaltaempleado;
    consulta ventanaconsulta;
    salida ventanasalida;
    Empleado e = new Empleado();
    
    int idemp;
    
    Registro registro;
    String q;
    public static String empleadoactivo="";
    int idactivo;

    public int getIdactivo() {
        return idactivo;
    }

    public void setIdactivo(int idactivo) {
        this.idactivo = idactivo;
    }

    public String getEmpleadoactivo() {
        return empleadoactivo;
    }

    public void setEmpleadoactivo(String empleadoactivo) {
        this.empleadoactivo = empleadoactivo;
    }
    
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        obtenerEmpleados();
        
     
    }
    
    public void obtenerEmpleados(){
        ArrayList<Empleado> empleados = new ArrayList<Empleado>();
         ArrayList<String> lista = new ArrayList<String>();
         registro = new Registro();
        q="From Empleado";
        empleados= (ArrayList<Empleado>) registro.consultar(q);
        lista.add("Seleccione");
        for (Empleado t: empleados) {
            
            lista.add(t.getIdempleado()+" "+t.getNombre());
            
            
        }
        for (int i = 0; i < lista.size(); i++) {
            comboempleados.addItem(lista.get(i));
        }
        comboempleados.addItemListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonIngreso = new javax.swing.JButton();
        ButtonSalida = new javax.swing.JButton();
        ButtonConsulta = new javax.swing.JButton();
        ButtonAltaCliente = new javax.swing.JButton();
        ButtonAltaEmpleado = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboempleados = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("menu");

        ButtonIngreso.setText("Registrar Ingreso");
        ButtonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresoActionPerformed(evt);
            }
        });

        ButtonSalida.setText("Registrar Salida");
        ButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalidaActionPerformed(evt);
            }
        });

        ButtonConsulta.setText("Consultas");
        ButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultaActionPerformed(evt);
            }
        });

        ButtonAltaCliente.setText("Agregar Cliente Nuevo");
        ButtonAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAltaClienteActionPerformed(evt);
            }
        });

        ButtonAltaEmpleado.setText("Agregar empleado");
        ButtonAltaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAltaEmpleadoActionPerformed(evt);
            }
        });

        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboempleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboempleadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboempleadosMousePressed(evt);
            }
        });
        comboempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboempleadosActionPerformed(evt);
            }
        });

        jLabel2.setText("Empleado activo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(ButtonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(ButtonAltaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonAltaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(comboempleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(127, 127, 127)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboempleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAltaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAltaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAltaClienteActionPerformed
        ventanaaltacliente = new altacliente();
        ventanaaltacliente.setVisible(true);
        
             
    }//GEN-LAST:event_ButtonAltaClienteActionPerformed

    private void ButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalidaActionPerformed
        
        
        if(empleadoactivo!=""){
        ventanasalida = new salida();
        ventanasalida.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Seleccione un empleado");
        
        
    }//GEN-LAST:event_ButtonSalidaActionPerformed

    private void ButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultaActionPerformed
        ventanaconsulta = new consulta();
        ventanaconsulta.setVisible(true);
    }//GEN-LAST:event_ButtonConsultaActionPerformed

    private void ButtonAltaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAltaEmpleadoActionPerformed
        ventanaaltaempleado = new altaempleado(); 
        ventanaaltaempleado.setVisible(true);
        
    }//GEN-LAST:event_ButtonAltaEmpleadoActionPerformed

    private void ButtonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresoActionPerformed
        
        if(empleadoactivo!=""){
        ventanaingreso = new ingresovehiculo();
        
        ventanaingreso.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Seleccione un empleado");
    
    }//GEN-LAST:event_ButtonIngresoActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void comboempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboempleadosActionPerformed
        
         
       // empleadoactivo=
        
    }//GEN-LAST:event_comboempleadosActionPerformed

    private void comboempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboempleadosMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_comboempleadosMouseClicked

    private void comboempleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboempleadosMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboempleadosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAltaCliente;
    private javax.swing.JButton ButtonAltaEmpleado;
    private javax.swing.JButton ButtonConsulta;
    private javax.swing.JButton ButtonIngreso;
    private javax.swing.JButton ButtonSalida;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JComboBox<String> comboempleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        
        if (e.getSource()==comboempleados) {
            if(comboempleados.getSelectedItem().toString()!="Seleccione")
            {
            empleadoactivo=comboempleados.getSelectedItem().toString();
            System.out.println(empleadoactivo);
            }
        else
                empleadoactivo="";
        }
    }
}
