package modelo;
// Generated 16/06/2020 17:55:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private long dni;
     private String nombre;
     private long telefono;
     private String direccion;
     
     private Set vehiculos;

    public Cliente() {
    }

	
    public Cliente(long dni, String nombre, long telefono, String direccion) {
        this.dni = dni;
        this.nombre = nombre;
        this.telefono = telefono;
        this.direccion = direccion;
    }
    public Cliente(long dni, String nombre, long telefono, String direccion, Set vehiculos) {
       this.dni = dni;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.vehiculos = vehiculos;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public long getDni() {
        return this.dni;
    }
    
    public void setDni(long dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(long telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }



     @Override
    public String toString(){
        
        return ("IDCliente: "+idcliente+"\nNombre: "+nombre);
    }
    
    public void calcular_precioxhora(){
        
        precios p = new precios();
        Set<Vehiculo> vehiculo= this.vehiculos;
        for(Vehiculo v: vehiculo){
            
            if(v.getTipo().equals("Moto"))
                v.setPrecioHora(p.getMotoxhora());
            else
                v.setPrecioHora(p.getAutoxhora());
            
        }
    }
}


