package modelo;
// Generated 16/06/2020 17:55:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private Integer idvehiculo;
     private Cliente cliente;
     private String patente;
     private String tipo;
     private String color;
     private String marca;
     private double precioHora;
     private Boolean estado;
     private Set registros = new HashSet(0);
     
     


    public Vehiculo() {
    }

	
    public Vehiculo(String patente, String tipo, String color, String marca) {
        
        this.patente = patente;
        this.tipo = tipo;
        this.color = color;
        this.marca = marca;
        this.precioHora =0.0;
        this.estado = false;
       
        
    }
    public Vehiculo(Cliente cliente, String patente, String tipo, String color, String marca, double precioHora, Boolean estado, Set registros) {
       this.cliente = cliente;
       this.patente = patente;
       this.tipo = tipo;
       this.color = color;
       this.marca = marca;
       this.precioHora = precioHora;
       this.estado = estado;
       this.registros = registros;
    }
   
    public Integer getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(Integer idvehiculo) {
        this.idvehiculo = idvehiculo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getPatente() {
        return this.patente;
    }
    
    public void setPatente(String patente) {
        this.patente = patente;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public double getPrecioHora() {
        return this.precioHora;
    }
    
    public void setPrecioHora(double precioHora) {
        this.precioHora = precioHora;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }

    
    
     @Override
    public String toString(){
        
        return ("patente:"+patente+"\nTipo: "+tipo+"\nMarca: "+marca);
       
    }
    
   
}


